version: "3.1"

services:
  api_server:
    image: cosmicbox-api
    build: ./
    command: server
    ports:
      - "9000:9000"
    environment:
      GIN_MODE: "release"
      DB_DRIVER: "postgres"
      DB_CONFIG: "postgres://cosmic:safe-password@database:5432/cosmic?sslmode=disable"
      COSMIC_DEBUG: "1"
      CREDENTIALS_FILE: /run/secrets/oauth-config-dev
      # REDIRECT_URL: "http:/localhost:9000/auth"
    secrets:
      - oauth-config-dev
  database:
    image: postgres:10.0-alpine
    volumes:
      - cosmic-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "safe-password"
      POSTGRES_USER: "cosmic"
      POSTGRES_DB: "cosmic"

secrets:
  oauth-config-dev:
    file: oauth_secret_dev.json

volumes:
  cosmic-data:
    driver: local
